### ISSUE TITLE
Circular-lineked-list 

### ISSUE THREAD

**Issue by wangfpp** [PacktPublishing/Learning-JavaScript-Data-Structures-and-Algorithms-Third-Edition#10]
### What‘s happend？？？
![image](https://user-images.githubusercontent.com/35289556/115533379-41bd8e00-a2c9-11eb-9c86-b87ec557f1ee.png)

**Comment by loiane** [comment]
Hi, what edition is this? Code has been updated in the latest edition.

**Comment by wangfpp** [comment]
Hi Thank you for your reply. I read the third edition
