### ISSUE TITLE
Calculation of the number of elements in bucket sorting

### ISSUE THREAD

**Issue by PachVerb** [PacktPublishing/Learning-JavaScript-Data-Structures-and-Algorithms-Third-Edition#11]
Hello, I am learning bucket sorting. I don't understand the logic of a piece of code very well; or it is about the principle of calculating the number of elements in the bucket sorting bucket. code show as below:

```javascript
....
const buketCount: number =
    Math.floor((maxValue - minxValue) / bucketsSize) + 1;   // --> Why is it necessary to add 1 when calculating the number of elements in the bucket?  I do not really understand.
  const bukets: number[][] = [];
  for (let i: number = 0; i < buketCount; i++) {
    bukets[i] = [];
  }
....
```
If you see, I hope to help me explain, thank you very much

**Comment by zhyd1997** [comment]
> Why is it necessary to add 1 when calculating the number of elements in the bucket?  I do not really understand.

it is related to `for (let i = 0; i < bucketCount; i++)`,

`i` is less than `bucketCount`, 

it can not be equal to that, 

if we don't plus 1, we could lose one elements in bucket.

**Comment by PachVerb** [comment]
> > Why is it necessary to add 1 when calculating the number of elements in the bucket?  I do not really understand.
> 
> it is related to `for (let i = 0; i < bucketCount; i++)`,
> 
> `i` is less than `bucketCount`,
> 
> it can not be equal to that,
> 
> if we don't plus 1, we could lose one elements in bucket.

Yes, I seem to understand. Thank you.
