### ISSUE TITLE
AVL-tree removeNode func is not correct

### ISSUE THREAD

**Issue by huiliangShen** [PacktPublishing/Learning-JavaScript-Data-Structures-and-Algorithms-Third-Edition#14]
https://github.com/PacktPublishing/Learning-JavaScript-Data-Structures-and-Algorithms-Third-Edition/blob/520e02f041966400fa957bc1a3317b2dc9db4a96/LearningJavaScriptDataStructuresandAlgorithmsThirdEdition_Code/src/js/data-structures/avl-tree.js#L125-L159
```js
     // Left right case 
     if (this.getBalanceFactor(node.left) === BalanceFactor.SLIGHTLY_UNBALANCED_RIGHT) { 
       return this.rotationLR(node.left); 
     } 
```
I think this code is not correct;
eg:
```
                      10
                 ↙          ↘  
            6                     。。。
        ↙       ↘         
      3             8       
         ↘       
             4
```
1. remove node `key = 8`;
2. node `key=6` is not balanced;
3. condition accord with `balanceFactor === BalanceFactor.UNBALANCED_RIGHT `;
4. run `return this.rotationLR(node.left);`, it's will be throw error;

##### in fact, this condition need `return this.rotationLR(node)`;

also, Right-left-case has same error
```js
 // Right left case
  if (this.getBalanceFactor(node.right) === BalanceFactor.SLIGHTLY_UNBALANCED_LEFT) {
       // need change code
        return this.rotationRL(node.right);
        ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
        return this.rotationRL(node);
   }
```

**Comment by loiane** [comment]
Thanks for the fix, can you please open a PR with this fix?

**Comment by huiliangShen** [comment]
> Thanks for the fix, can you please open a PR with this fix?

It's my pleasure
